name: Deploy to Trigger.dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22.14.0
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build-sdk
      - name: Deploy to production
        if: github.event_name == 'push'
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_PRODUCTION_ACCESS_TOKEN }}
        working-directory: apps/studio.giselles.ai
        run: pnpm dlx trigger.dev@4.1.0 deploy
      - name: Deploy to staging
        if: github.event_name == 'workflow_dispatch'
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_STAGING_ACCESS_TOKEN }}
        working-directory: apps/studio.giselles.ai
        run: pnpm dlx trigger.dev@4.1.0 deploy --env staging
